# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{arel-mongo}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["akdubya"]
  s.date = %q{2010-05-15}
  s.description = %q{Arel Mongo is a MongoDB engine for Arel featuring support
for embedded documents, modifiers and other Mongo-specific features.}
  s.email = %q{alekswilliams@earthlink.net}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "arel-mongo.gemspec",
     "lib/arel-mongo.rb",
     "lib/arel-mongo/algebra.rb",
     "lib/arel-mongo/algebra/attributes.rb",
     "lib/arel-mongo/algebra/attributes/array.rb",
     "lib/arel-mongo/algebra/attributes/attribute.rb",
     "lib/arel-mongo/algebra/attributes/binary.rb",
     "lib/arel-mongo/algebra/attributes/date.rb",
     "lib/arel-mongo/algebra/attributes/date_time.rb",
     "lib/arel-mongo/algebra/attributes/element.rb",
     "lib/arel-mongo/algebra/attributes/generic.rb",
     "lib/arel-mongo/algebra/attributes/hash.rb",
     "lib/arel-mongo/algebra/attributes/object_id.rb",
     "lib/arel-mongo/algebra/attributes/regexp.rb",
     "lib/arel-mongo/algebra/attributes/symbol.rb",
     "lib/arel-mongo/algebra/attributes/time.rb",
     "lib/arel-mongo/algebra/core_extensions/hash.rb",
     "lib/arel-mongo/algebra/modifiers.rb",
     "lib/arel-mongo/algebra/predicates.rb",
     "lib/arel-mongo/algebra/relations.rb",
     "lib/arel-mongo/algebra/relations/operations/set.rb",
     "lib/arel-mongo/algebra/relations/relation.rb",
     "lib/arel-mongo/algebra/relations/utilities/compound.rb",
     "lib/arel-mongo/engines.rb",
     "lib/arel-mongo/engines/memory.rb",
     "lib/arel-mongo/engines/memory/relations/array.rb",
     "lib/arel-mongo/engines/memory/relations/operations/set.rb",
     "lib/arel-mongo/engines/mongo.rb",
     "lib/arel-mongo/engines/mongo/core_extensions.rb",
     "lib/arel-mongo/engines/mongo/core_extensions/array.rb",
     "lib/arel-mongo/engines/mongo/core_extensions/hash.rb",
     "lib/arel-mongo/engines/mongo/core_extensions/object.rb",
     "lib/arel-mongo/engines/mongo/engine.rb",
     "lib/arel-mongo/engines/mongo/formatters.rb",
     "lib/arel-mongo/engines/mongo/modifiers.rb",
     "lib/arel-mongo/engines/mongo/predicates.rb",
     "lib/arel-mongo/engines/mongo/primitives.rb",
     "lib/arel-mongo/engines/mongo/relations.rb",
     "lib/arel-mongo/engines/mongo/relations/collection.rb",
     "lib/arel-mongo/engines/mongo/relations/cursor.rb",
     "lib/arel-mongo/engines/mongo/relations/document.rb",
     "lib/arel-mongo/engines/mongo/relations/embedded.rb",
     "lib/arel-mongo/engines/mongo/relations/relation.rb",
     "lib/arel-mongo/engines/mongo/relations/utilities/compound.rb",
     "lib/arel-mongo/engines/mongo/relations/writes.rb",
     "lib/arel-mongo/engines/mongo/utilities/mongo.rb",
     "lib/arel-mongo/version.rb",
     "spec/algebra/unit/relations/union_spec.rb",
     "spec/engines/memory/relations/unit/union_spec.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb",
     "spec/unit/engine/create_spec.rb",
     "spec/unit/engine/delete_spec.rb",
     "spec/unit/engine/read_spec.rb",
     "spec/unit/engine/update_spec.rb",
     "spec/unit/modifiers/binary_spec.rb",
     "spec/unit/modifiers/unset_spec.rb",
     "spec/unit/predicates/binary_spec.rb",
     "spec/unit/predicates/elem_match_spec.rb",
     "spec/unit/predicates/equality_spec.rb",
     "spec/unit/predicates/in_spec.rb",
     "spec/unit/predicates/match_spec.rb",
     "spec/unit/primitives/attribute_spec.rb",
     "spec/unit/primitives/element_spec.rb",
     "spec/unit/relations/array_spec.rb",
     "spec/unit/relations/collection_spec.rb",
     "spec/unit/relations/insert_spec.rb",
     "spec/unit/relations/relation_spec.rb"
  ]
  s.homepage = %q{http://github.com/akdubya/arel-mongo}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{MongoDB engine for Arel}
  s.test_files = [
    "spec/algebra/unit/relations/union_spec.rb",
     "spec/engines/memory/relations/unit/union_spec.rb",
     "spec/spec_helper.rb",
     "spec/unit/modifiers/unset_spec.rb",
     "spec/unit/modifiers/binary_spec.rb",
     "spec/unit/predicates/in_spec.rb",
     "spec/unit/predicates/equality_spec.rb",
     "spec/unit/predicates/binary_spec.rb",
     "spec/unit/predicates/match_spec.rb",
     "spec/unit/predicates/elem_match_spec.rb",
     "spec/unit/relations/relation_spec.rb",
     "spec/unit/relations/array_spec.rb",
     "spec/unit/relations/insert_spec.rb",
     "spec/unit/relations/collection_spec.rb",
     "spec/unit/engine/create_spec.rb",
     "spec/unit/engine/read_spec.rb",
     "spec/unit/engine/delete_spec.rb",
     "spec/unit/engine/update_spec.rb",
     "spec/unit/primitives/attribute_spec.rb",
     "spec/unit/primitives/element_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
    else
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
  end
end

